apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dev
  labels:
    app: kube-dev
  namespace: revnet-taskapp-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-dev
  template:
    metadata:
      labels:
        app: kube-dev
    spec:
      containers:
        - name: kube-dev
          image: taskappdev.azurecr.io/revnet-taskapp-api-dev:latest
          ports:
            - containerPort: 3000
