apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-dev-automatic
  labels:
    app: taskapp-dev-automatic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp-dev-automatic
  template:
    metadata:
      labels:
        app: taskapp-dev-automatic
    spec:
      containers:
        - name: taskapp-dev-automatic
          image: taskappdev.azurecr.io/image-workflow-1686443833571:latest
          ports:
            - containerPort: 3000