apiVersion: v1
kind: Service
metadata:
  name: taskapp-dev-automatic
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: taskapp-dev-automatic
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000